# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ko_fi: Ian7672 
custom: 
  - https://www.paypal.me/luqmanijsp
  - https://trakteer.id/Ian7672
  - https://linktr.ee/Ian7672
